In [221]:
# !python -m pip install geopandas
import pandas as pd
import numpy as np
import geopandas as gpd
import os
import glob

In [222]:
# read preharvest data
preharvest_data=pd.read_csv('data/preharvest/zambia_preharvest_district_data_clean.csv')
cultivars=pd.read_csv('data/cultivartests/cultivars/all_cultivars.csv')

# select only for 2011 to 2021
preharvest=preharvest_data.loc[(preharvest_data['year']>=2011)&(preharvest_data['year']<=2021)]

# # Read cultivar data
# import re
# from pathlib import Path    
# # >>> Path("/tmp/d/a.dat").name
# # 'a.dat'
# notempty_files=[]
# all_files= glob.glob('D:/RONO/rheas/maize_crop_modeling/crop-modeling/zambia/data/cultivartests/cultivars/*.csv')
# # empty_files1=glob.glob('D:/RONO/cultivars/maize_crop_modeling/crop-modeling/zambia/data/cultivartests/cultivars/*2022.csv')
# # empty_files=glob.glob('D:/RONO/cultivars/maize_crop_modeling/crop-modeling/zambia/data/cultivartests/cultivars/*2023.csv')
# # for i in empty_files1:
# #     empty_files.append(i)

# for file in all_files:
#     # print(file)
#     # notempty_files.append(file)
#     cultivars4=pd.read_csv(file)
#     x=Path(file).name
#     # x=name.strip('_.*csv')
#     # cultivars4['cultivar']=Path(file).name.replace('.csv', '')
#     cultivars4['cultivar'] = re.sub(r'_\d\d\d\d.csv', '', x)
#     notempty_files.append(cultivars4)
#     cultivars=pd.concat(notempty_files, axis=1)
# # cultivars.to_csv('data/cultivartests/cultivars/all_cultivars.csv')
# cultivars
preharvest

,district,year,planted_ha,harvested_ha,production_mt,yield(mt/ha),yield,yield_h,zyield,flag
0,chadiza,2011,21879,21293,42951,1.96,1.963115,2.017142,-0.513418,0
1,chadiza,2012,23894,21453,51340,2.15,2.148657,2.393138,-0.050325,0
2,chadiza,2013,24901,23476,50022,2.01,2.008835,2.130772,-0.399306,0
3,chadiza,2014,25395,22957,61135,2.41,2.407364,2.663022,0.595381,0
4,chadiza,2015,25379,21825,51345,2.02,2.023129,2.352577,-0.363629,0
...,...,...,...,...,...,...,...,...,...,...
880,zambezi,2017,6650,5109,9911,1.49,1.490376,1.939910,-0.874990,0
881,zambezi,2018,4682,3941,7595,1.62,1.622170,1.927176,-0.559302,0
882,zambezi,2019,5885,3990,6973,1.18,1.184877,1.747619,-1.606755,0
883,zambezi,2020,7193,6031,12153,1.69,1.689559,2.015089,-0.397884,0
884,zambezi,2021,6350,5533,18935,2.98,2.981890,3.422194,2.697649,2

In [223]:
# # Read cultivar data
# import re
# from pathlib import Path    
# # >>> Path("/tmp/d/a.dat").name
# # 'a.dat'
# notempty_files=[]
# all_files= glob.glob('D:/RONO/rheas/maize_crop_modeling/crop-modeling/zambia/data/cultivartests/cultivars/*.csv')
# # empty_files1=glob.glob('D:/RONO/cultivars/maize_crop_modeling/crop-modeling/zambia/data/cultivartests/cultivars/*2022.csv')
# # empty_files=glob.glob('D:/RONO/cultivars/maize_crop_modeling/crop-modeling/zambia/data/cultivartests/cultivars/*2023.csv')
# # for i in empty_files1:
# #     empty_files.append(i)

# for file in all_files:
#     if file not in all_files:
#         pass
#     else:
#         # print(file)
#         # notempty_files.append(file)
#         cultivars4=pd.read_csv(file)
#         x=Path(file).name
#         # x=name.strip('_.*csv')
#         # cultivars4['cultivar']=Path(file).name.replace('.csv', '')
#         cultivars4['cultivar'] = re.sub(r'_\d\d\d\d.csv', '', x)
#         notempty_files.append(cultivars4)
#         cultivars=pd.concat(notempty_files, axis=1)
# # cultivars.to_csv('data/cultivartests/cultivars/all_cultivars.csv')
# cultivars

In [224]:
#changing date columns and rename to district
cultivars['planting']=pd.to_datetime(cultivars['planting'], format='ISO8601')
cultivars['harvest'] = pd.to_datetime(cultivars['harvest'], format='ISO8601')
cultivars['year'] = cultivars['planting'].dt.year
cultivars['district']=cultivars['cname']
cultivars['yield']=cultivars['gwad']/1000

In [225]:
# # remove all white spaces, turn to lower case and
cultivars.cname=cultivars.cname.str.lower()
cultivars.cname = cultivars.cname.str.strip()
cultivars.cname=cultivars.cname.str.replace('-', '', regex=True)
cultivars.cname=cultivars.cname.str.replace(' ', '', regex=True)

In [226]:
#changing date columns
cultivars['planting']=pd.to_datetime(cultivars['planting'], format='ISO8601')
cultivars['harvest'] = pd.to_datetime(cultivars['harvest'], format='ISO8601')
cultivars['year'] = cultivars['planting'].dt.year
cultivars['district']=cultivars['cname']
cultivars['yield']=cultivars['gwad']/1000
cultivars

,Unnamed: 0,cname,planting,harvest,gwad,cultivar,year,district,yield,season1
0,0,chadiza,2011-10-15,2012-01-24,4394,cultivar10,2011,chadiza,4.394,1
1,1,chadiza,2011-10-15,2012-01-24,4424,cultivar10,2011,chadiza,4.424,1
2,2,chadiza,2011-10-15,2012-01-24,4459,cultivar10,2011,chadiza,4.459,1
3,3,chadiza,2011-10-17,2012-01-29,4388,cultivar10,2011,chadiza,4.388,1
4,4,chadiza,2011-10-17,2012-01-29,4350,cultivar10,2011,chadiza,4.350,1
...,...,...,...,...,...,...,...,...,...,...
1275827,11592,zimba,2022-01-28,2022-06-17,6690,cultivar9,2022,zimba,6.690,1
1275828,11593,zimba,2022-01-28,2022-06-17,6057,cultivar9,2022,zimba,6.057,1
1275829,11594,zimba,2022-01-29,2022-06-19,7532,cultivar9,2022,zimba,7.532,1
1275830,11595,zimba,2022-01-29,2022-06-19,6371,cultivar9,2022,zimba,6.371,1
1275831,11596,zimba,2022-01-30,2022-06-20,6203,cultivar9,2022,zimba,6.203,1

In [227]:
# #Derive seasons and add to cultivars data
# seasons = [1, 1, 1, 1,1, 0, 0, 0, 0, 1, 1, 1]
# month_to_season=dict(zip(range(1,13), seasons))
# cultivars['season1']= cultivars['planting'].dt.month.map(month_to_season)

def rheas_to_season(data):
    cultivars4=[]
    season_list = [2, 2, 2, 2,2, 2, 0, 0, 0, 1, 1, 1]
    month_to_season=dict(zip(range(1,13), season_list ))
    data['season2']= data['planting'].dt.month.map(month_to_season)
    # Extract data only for the seasons
    part1= data.loc[data['season2']==1]
    part2= data.loc[data['season2']==2]
    part3=pd.concat([part1, part2], axis=0, ignore_index=True)
    rheas_part1= part3.loc[part3['season2']==1]
    rheas_part2= part3.loc[part3['season2']==2]
    part4=pd.concat([rheas_part1, rheas_part2], axis=0, ignore_index=True)
    for year in list(part4.year.unique()):
       df1=rheas_part1.loc[rheas_part1['year']==year]
       df2=rheas_part2.loc[rheas_part2['year']==year+1]
       df3=pd.concat([df1, df2], axis=0, ignore_index=True)
       df3['season_year']=year
       cultivars4.append(df3)
       df4=pd.concat(cultivars4,axis=0,ignore_index=True)
       df5=df4.groupby(['district','season_year','cultivar','year'],as_index=False).agg({'yield':'mean'})
    return df5

cultivars=rheas_to_season(data=cultivars)
# cultivars.to_csv('data/cultivartests/cultivars/all_cultivars_seasonyear.csv')
cultivars

      district  season_year    cultivar  year    yield
0      chadiza         2011   cultivar1  2011  3.84704
1      chadiza         2011   cultivar1  2012  4.37038
2      chadiza         2011  cultivar10  2011  4.76036
3      chadiza         2011  cultivar10  2012  5.02104
4      chadiza         2011   cultivar2  2011  3.86252
...        ...          ...         ...   ...      ...
25515    zimba         2021   cultivar7  2022  7.01780
25516    zimba         2021   cultivar8  2021  6.59672
25517    zimba         2021   cultivar8  2022  6.06038
25518    zimba         2021   cultivar9  2021  5.75058
25519    zimba         2021   cultivar9  2022  6.46514

[25520 rows x 5 columns]

In [228]:
# # aggregate data
# cultivar_yearly=cultivars_season.groupby(['district', 'season1', 'year'], as_index=False).agg({'yield':'mean'})
# preharvest_yearly=preharvest.groupby(['district', 'year'], as_index=False).agg({'yield':'mean'})
# cultivar_yearly

In [229]:
#Extracting Districts list
#first set cname to district
# cultivars['district']=cultivars['cname']

preharvest_list_districts= preharvest['district'].to_list()
preharvest_set_districts=set(preharvest_list_districts)
preharvest_districts=list(preharvest_set_districts)
cultivars_list_districts=cultivars['district'].to_list()
cultivars_set_districts=set(cultivars_list_districts)
cultivars_districts=list(cultivars_set_districts)

In [230]:
# #Extracting Districts list
# #first set cname to district
# cultivars['district']=cultivars['cname']

# preharvest_list_districts= preharvest['district'].to_list()
# preharvest_set_districts=set(preharvest_list_districts)
# preharvest_districts=list(preharvest_set_districts)
# cultivars_list_districts=cultivars['district'].to_list()
# cultivars_set_districts=set(cultivars_list_districts)
# cultivars_districts=list(cultivars_set_districts)

In [231]:
# list of cultivars
cultivars_list=list(cultivars.cultivar.unique())
cultivars_list

['cultivar1',
 'cultivar10',
 'cultivar2',
 'cultivar3',
 'cultivar4',
 'cultivar5',
 'cultivar6',
 'cultivar7',
 'cultivar8',
 'cultivar9']

In [232]:
cultivar_list1=[]
for c in cultivars_list:
    cultivars11=cultivars.loc[cultivars['cultivar']==c]
    cultivar_list1.append(cultivars11)
    cultivars4=pd.concat(cultivar_list1)
cultivars4

      district  season_year   cultivar  year    yield
0      chadiza         2011  cultivar1  2011  3.84704
1      chadiza         2011  cultivar1  2012  4.37038
20     chadiza         2012  cultivar1  2012  3.48792
21     chadiza         2012  cultivar1  2013  4.50510
40     chadiza         2013  cultivar1  2013  3.79452
...        ...          ...        ...   ...      ...
25479    zimba         2019  cultivar9  2020  5.85298
25498    zimba         2020  cultivar9  2020  6.39446
25499    zimba         2020  cultivar9  2021  5.98302
25518    zimba         2021  cultivar9  2021  5.75058
25519    zimba         2021  cultivar9  2022  6.46514

[25520 rows x 5 columns]

In [ ]:
cultivars4 = cultivars4.reset_index()
stats = pd.DataFrame()

for c in cultivars4.cultivar.unique():
    for p in cultivars4.district.unique():
        pre1 = preharvest.loc[preharvest['district']==p]
        df2 = cultivars4.loc[((cultivars4['district']==p)&(cultivars4['cultivar']==c))]


        # get average season length in days for each cultivar
        try:
            df2['harvest'] = pd.to_datetime(df2['harvest'])
            df2['planting'] = pd.to_datetime(df2['planting'])
            
            df2['slength'] = (df2['harvest']-df2['planting']).dt.days
            slength = df2['slength'].mean()
        except:
            slength = np.NaN

        
        pre1 = pre1.set_index(['district','year'])
        df2 = df2.groupby(['district','year']).mean()
        
        # combine the two dataframes: note that here the yield is stored in column 'gwad' for dssat
        # and column 'yield' for the survey data
        # note that if there are years that one dataset has data for that the other doesn't
        # the years that are not present will be filled with NaNs
        df1 = pd.concat([pre1,df2],axis=1)
        

        # calculate statistics one province at a time and append to a new dataframe
        # correlation
        corr = df1['gwad'].corr(df1['yield'])
        # root mean square error
        rmse = np.sqrt(((df1['gwad']-df1['yield'])**2).mean())
        # percentage rmse
        perrmse = np.sqrt(((df1['gwad']-df1['yield'])**2).mean())/(df1['yield'].mean())*100
        # unbiased rmse
        ubrmse = np.sqrt((((df1['gwad']-df1['gwad'].mean())-(df1['yield']-df1['yield'].mean()))**2).mean())
        # bias
        bias = (df1['gwad']-df1['yield']).mean()
        stats = stats.append({'district':p,'cultivar':c, 'rmse':rmse, '%rmse':perrmse,'unbiased rmse':ubrmse, 'bias':bias, 'correlation':corr, 'season length':slength}, ignore_index=True)

# save statistics as a csv
# stats.to_csv(wdir+'districteval.csv')

###############################################################################

# select best cultivars for each district given the statistics
culs = pd.read_csv(wdir+'districteval.csv')
selected = pd.DataFrame()

for p in culs.district.unique():

        cultivars4 = culs.loc[culs['district']==p]
        # remove cultivars that have a season length shorter than expected
        earliestharvest = 100 # shortest expected season length in days
        cultivars4 = cultivars4.loc[cultivars4['season length']>=earliestharvest]
        # select cultivars with correlation above 0.8 and the lowest ubrmse
        df1 = cultivars4.loc[cultivars4['correlation']>=0.8]
        if df1.empty:
            # if no cultivars have correlation above 0.8 select the cultivar with highest correlation
            df1 = cultivars4.loc[cultivars4['correlation'] == cultivars4['correlation'].max()]
        else: 
            df1 = df1.loc[df1['unbiased rmse'] == df1['unbiased rmse'].min()]
        selected = pd.concat([selected,df1])

# save stats and cultivar number of selected cultivars to a csv
selected.to_csv(wdir+'cultivartests_selected.csv')

# add the dssat outputs from only the selected cultivars to one csv
yields = pd.read_csv(wdir+'allcultivars.csv')
selected = pd.read_csv(wdir+'cultivartests_selected.csv')
yields2 = pd.DataFrame()

for c in selected.district.unique():
    sn = selected.loc[(selected['county']==c)]
    cultivars4 = selected.loc[((selected['county']==c))]
    y1 = yields.loc[((yields['cname']==c))]
    cul = cultivars4['cultivar'].item()
    y2 = y1.loc[y1['cultivar']==cul]
    yields2 = pd.concat([yields2,y2])

yields2.to_csv(wdir+'cultivarselectedyields.csv')

In [9]:
# cultivars and preharvest metrics
# preharvest is 2011 to 2022
rheas_preharvest_districts=preharvest_districts
district_rheas_prehavest=cultivar_yearly.loc[(cultivar_yearly['year']>=2011)&(cultivar_yearly['year']<=2021)]
rheas_preharvest_disct_check=[]
distric_metrics1=[]

for i in rheas_preharvest_districts:
        district_preharvest=preharvest_yearly.loc[preharvest_yearly['district']==i].reset_index(drop=True)
        cultivars_data3=district_rheas_prehavest.loc[district_rheas_prehavest['district']==i].reset_index(drop=True)
        #  pearson's correlation
        corr=cultivars_data3['yield'].corr(district_preharvest['yield'])
        # # #root mean square error
        rmse = np.sqrt(((cultivars_data3['yield']-district_preharvest['yield'])**2).mean())
        # # #unbiased RMSE
        ubrmse = np.sqrt((((cultivars_data3['yield']-cultivars_data3['yield'].mean())
                    -(district_preharvest['yield']-district_preharvest['yield'].mean()))**2).mean())
        # #bias
        bias = (cultivars_data3['yield']-district_preharvest['yield']).mean()
        distric_metrics1.extend([[i, corr,rmse,ubrmse,bias]])
        # convert into dataframe and rename column
        rheas_preharvest_disct_check.append(district_preharvest)

check_rheas_preharvest_disct= pd.concat(cultivars_preharvest_disct_check, ignore_index=True)
district_cultivars_preharvest_metrics1=pd.DataFrame(distric_metrics1)
district_cultivars_preharvest_metrics=district_cultivars_preharvest_metrics1.rename({0:'district',1: 'correlation', 2: 
                                                    'rmse', 3:'ubrmse', 4:'bias'}, axis=1)
district_cultivars_preharvest_metrics

     district  correlation      rmse    ubrmse      bias
0     chongwe     0.024376  1.194097  0.322518  1.149718
1       mpika     0.277966  0.420741  0.249267  0.338953
2   nchelenge    -0.270999  1.389866  0.454236  1.313544
3     kasempa     0.381782  0.731690  0.239792  0.691281
4      mkushi     0.247837  0.583331  0.570925  0.119665
..        ...          ...       ...       ...       ...
69   siavonga     0.570296  2.199657  0.379953  2.166594
70      kitwe    -0.200951  1.239024  0.435197  1.160079
71    senanga     0.208361  3.053119  0.234977  3.044064
72     kaputa    -0.531496  1.710629  0.600358  1.601819
73     kalomo     0.298046  1.821977  0.474294  1.759161

[74 rows x 5 columns]

In [10]:
# saven district metrics
district_cultivars_preharvest_metrics.to_csv('data/metrics/preharvest_cultivars_district_metrics.csv',index=False)

In [11]:
# Extract cultivars data only for  districts in preharvest
districts
datasets=district_cultivars_prehavest
district_cultivars_pre_list=[]
for i in districts:
    cultivarst_pre_dist_df=district_cultivars_prehavest.loc[district_cultivars_prehavest['district']==i]
    district_cultivars_pre_list.append(cultivarst_pre_dist_df)
cultivars_pre_common=pd.concat(district_cultivars_pre_list, ignore_index=True)
cultivars_pre_common
# district_rheas_prehavest.loc[datasets['district']!='kalomo']

    district  season1  year    yield
0    chongwe        1  2011  3.98434
1    chongwe        1  2012  4.04181
2    chongwe        1  2013  4.12051
3    chongwe        1  2014  4.00839
4    chongwe        1  2015  3.98969
..       ...      ...   ...      ...
883   kalomo        1  2018  3.85768
884   kalomo        1  2019  3.78418
885   kalomo        1  2020  3.93403
886   kalomo        1  2021  4.06884
887   kalomo        1  2022  3.78635

[888 rows x 4 columns]

In [12]:
# cultivars and preharvestharvest merged with metrics
# bias correcting cultivars using preharvest over the province
rheas_pre_common=rheas_pre_common.groupby(['district'], as_index=False).agg({'yield':'mean'})
preharvest_yearly=preharvest_yearly.groupby(['district'],as_index=False).agg({'yield':'mean'})

# marge preharvest, metrics and cultivars cultivars yields
preharvest_yearly.rename(columns={'yield':'pre_yield'}, inplace=True)
district_rheas_preharvest_merged=pd.concat([rheas_pre_common,preharvest_yearly,district_rheas_preharvest_metrics], axis=1)

# calculate bias corrected yield
district_rheas_preharvest_merged['corrected_yield']=district_rheas_preharvest_merged['yield']-district_rheas_preharvest_merged['bias']
district_rheas_preharvest_merged

,district,yield,district,pre_yield,district,correlation,rmse,ubrmse,bias,corrected_yield
0,chadiza,3.970162,chadiza,2.510959,chongwe,0.024376,1.194097,0.322518,1.149718,2.820444
1,chama,3.984371,chama,2.639932,mpika,0.277966,0.420741,0.249267,0.338953,3.645418
2,chavuma,3.988358,chavuma,2.662906,nchelenge,-0.270999,1.389866,0.454236,1.313544,2.674815
3,chibombo,3.972405,chibombo,2.541407,kasempa,0.381782,0.731690,0.239792,0.691281,3.281124
4,chiengi,3.980861,chiengi,2.605939,mkushi,0.247837,0.583331,0.570925,0.119665,3.861196
...,...,...,...,...,...,...,...,...,...,...
69,shangombo,3.987276,shangombo,0.992796,siavonga,0.570296,2.199657,0.379953,2.166594,1.820682
70,siavonga,3.973403,siavonga,1.806810,kitwe,-0.200951,1.239024,0.435197,1.160079,2.813324
71,sinazongwe,3.955806,sinazongwe,1.665775,senanga,0.208361,3.053119,0.234977,3.044064,0.911742
72,solwezi,3.979755,solwezi,2.094350,kaputa,-0.531496,1.710629,0.600358,1.601819,2.377936
73,zambezi,3.981637,zambezi,2.196392,kalomo,0.298046,1.821977,0.474294,1.759161,2.222476

In [13]:
# Province Level
# rename columns
preharvest['district_b']=preharvest['district']
cultivars_season['district_b']=cultivars_season['district']
postharvest['province_b']=postharvest['province']


#Read shapefiles and rename columns
zambia_district_shp = gpd.read_file('data/shp/zmb_district_cleaned.shp')
zambia_shp = gpd.read_file('../zambia/data/shp/gadm36_ZMB_0.shp')
zambia_province_shp = gpd.read_file('data/shp/zmb_province_cleaned.shp')

# merge the yields and shapefiles by provinces
preharvest_shp= pd.merge(zambia_district_shp, preharvest, on="district_b")
post_shp= pd.merge(zambia_province_shp, postharvest, on="province_b")
cultivars_shp= pd.merge(zambia_district_shp, cultivars_season, on="district_b")

# aggregate preharvestharvest to provincial level 
preharvest_provincial=preharvest_shp.groupby(['province_b','province', 'year'], as_index=False).agg({'harvested_ha':'sum', 'production_mt': 
                                                             'sum','planted_ha':'sum' })
preharvest_provincial['yield']=preharvest_provincial['production_mt']/preharvest_provincial['harvested_ha']
preharvest_provincial['yield_planted']=preharvest_provincial['production_mt']/preharvest_provincial['planted_ha']
cultivars_province=cultivars_shp.groupby(['province_b', 'province', 'year'], as_index=False).agg({'yield':'mean'})
post_province=post_shp.groupby(['province_b', 'year'], as_index=False).agg({'yield':'mean'})
post_province_rheas_post=post_province

In [14]:
provinces=['central', 'copperbelt', 'eastern', 'luapula', 'lusaka',
       'muchinga', 'northern', 'northwestern', 'southern', 'western']
rheas_provincial1=cultivars_province.loc[(cultivars_province['year']>=2011)&(cultivars_province['year']<=2022)]
rheas_provincial1=rheas_provincial1.reset_index()
rheas_preharvestharvest_province_metrics1=[]
rheas_preharvest_prov_check=[]
for i in provinces:
    preharvest_province1=preharvest_provincial.loc[preharvest_provincial['province_b']==i].reset_index(drop=True)
    cultivars_province1=rheas_provincial1.loc[rheas_provincial1['province_b']==i].reset_index(drop=True)  
    #  pearson's correlation
    corr=cultivars_province1['yield'].corr(preharvest_province1['yield'])

    # #root mean square error
    rmse = np.sqrt(((cultivars_province1['yield']-preharvest_province1['yield'])**2).mean())
    # #unbiased RMSE
    ubrmse = np.sqrt((((cultivars_province1['yield']-cultivars_province1['yield'].mean())
                       -(preharvest_province1['yield']-preharvest_province1['yield'].mean()))**2).mean())
    # #bias
    bias = (cultivars_province1['yield']-preharvest_province1['yield']).mean()
    # for i in districts:
    # metrics.extend([i, corr])
    rheas_preharvestharvest_province_metrics1.extend([[i, corr,rmse,ubrmse,bias]])
    # metrics.extend([i, corr])
    rheas_preharvest_prov_check.append(preharvest_province1)

check_rheas_preharvest_prov= pd.concat(rheas_preharvest_prov_check, ignore_index=True)
rheas_preharvest_prov_metric=pd.DataFrame(rheas_preharvestharvest_province_metrics1)
rheas_preharvestharvest_province_metric=rheas_preharvest_prov_metric.rename({0:'province',1: 'correlation',2: 
                                                  'rmse', 3:'ubrmse', 4:'bias'}, axis=1)
rheas_preharvestharvest_province_metric
# rheas_provincial1

       province  correlation      rmse    ubrmse      bias
0       central     0.379618  1.189460  0.302376  1.150385
1    copperbelt    -0.061651  1.069403  0.202911  1.049976
2       eastern     0.473370  1.772778  0.162292  1.765333
3       luapula     0.137104  0.986394  0.183999  0.969080
4        lusaka     0.287522  1.203676  0.335756  1.155900
5      muchinga     0.205617  0.536010  0.188335  0.501833
6      northern     0.571940  1.078418  0.225357  1.054608
7  northwestern    -0.390952  1.307819  0.347620  1.260774
8      southern     0.422918  1.811383  0.375846  1.771962
9       western     0.165242  2.651487  0.260853  2.638624

In [15]:
# save province metrics
rheas_preharvestharvest_province_metric.to_csv('data/metrics/preharvest_rheas_province_level_metrics.csv', index=False)

In [16]:
# cultivars and preharvestharvest merged with metrics
# bias correcting cultivars using preharvest over the province
rheas_provincial1=rheas_provincial1.groupby(['province_b'], as_index=False).agg({'yield':'mean'})
post_province_bias=post_province.groupby(['province_b'],as_index=False).agg({'yield':'mean'})

# marge preharvest, metrics and cultivars cultivars yields
post_province_renamed=post_province_bias.rename(columns={'yield':'post_yield'})
province_rheas_preharvest_merged=pd.concat([rheas_provincial1,post_province_renamed,rheas_preharvestharvest_province_metric], axis=1)

# calculate bias corrected yield
province_rheas_preharvest_merged['corrected_yield']=province_rheas_preharvest_merged['yield']-province_rheas_preharvest_merged['bias']
province_rheas_preharvest_merged.drop(columns={'province_b'})

,yield,post_yield,province,correlation,rmse,ubrmse,bias,corrected_yield
0,3.972415,2.078341,central,0.379618,1.189460,0.302376,1.150385,2.822031
1,3.968746,2.210160,copperbelt,-0.061651,1.069403,0.202911,1.049976,2.918770
2,3.973352,1.768208,eastern,0.473370,1.772778,0.162292,1.765333,2.208019
3,3.970544,2.554374,luapula,0.137104,0.986394,0.183999,0.969080,3.001463
4,3.974543,2.115439,lusaka,0.287522,1.203676,0.335756,1.155900,2.818643
5,3.986900,2.621986,muchinga,0.205617,0.536010,0.188335,0.501833,3.485066
6,3.980668,2.440774,northern,0.571940,1.078418,0.225357,1.054608,2.926060
7,3.982620,2.216512,northwestern,-0.390952,1.307819,0.347620,1.260774,2.721846
8,3.972499,1.314307,southern,0.422918,1.811383,0.375846,1.771962,2.200537
9,3.976332,0.736167,western,0.165242,2.651487,0.260853,2.638624,1.337707

In [17]:
# # Postharvest and cultivars common years 
post_list_years= postharvest['year'].to_list()
years_set=set(post_list_years)
post_harvest_years=list(years_set)
post_harvest_years

# df1=cultivars_province.loc[cultivars_province['year']==2016]
cultivars_province2=pd.DataFrame(columns =[cultivars_province.columns])

emptylist=[]
for i in post_harvest_years:
    cultivars4=cultivars_province.loc[cultivars_province['year']==i].reset_index(drop=True)
    emptylist.append(cultivars4)
dataset2=pd.concat(emptylist, ignore_index=True)
cultivars_province
cultivars_province2
dataset2

      province_b       province  year     yield
0        central        Central  2011  4.002420
1     copperbelt     Copperbelt  2011  4.017213
2        eastern        Eastern  2011  4.002530
3        luapula        Luapula  2011  4.001924
4         lusaka         Lusaka  2011  4.010953
5       muchinga       Muchinga  2011  4.013379
6       northern       Northern  2011  4.004577
7   northwestern  North-Western  2011  4.018557
8       southern       Southern  2011  4.005731
9        western        Western  2011  4.005729
10       central        Central  2012  3.989739
11    copperbelt     Copperbelt  2012  3.993824
12       eastern        Eastern  2012  3.988993
13       luapula        Luapula  2012  3.999297
14        lusaka         Lusaka  2012  3.990343
15      muchinga       Muchinga  2012  4.039760
16      northern       Northern  2012  4.005043
17  northwestern  North-Western  2012  4.002935
18      southern       Southern  2012  3.984121
19       western        Western  2012  3.999370
20       central        Central  2013  4.146444
21    copperbelt     Copperbelt  2013  4.170534
22       eastern        Eastern  2013  4.152863
23       luapula        Luapula  2013  4.150811
24        lusaka         Lusaka  2013  4.150313
25      muchinga       Muchinga  2013  4.161530
26      northern       Northern  2013  4.146193
27  northwestern  North-Western  2013  4.166444
28      southern       Southern  2013  4.141360
29       western        Western  2013  4.147315
30       central        Central  2014  3.988977
31    copperbelt     Copperbelt  2014  4.016149
32       eastern        Eastern  2014  3.998445
33       luapula        Luapula  2014  3.982065
34        lusaka         Lusaka  2014  3.998255
35      muchinga       Muchinga  2014  4.013826
36      northern       Northern  2014  3.991627
37  northwestern  North-Western  2014  3.994874
38      southern       Southern  2014  3.993524
39       western        Western  2014  3.989649

In [18]:
# Postharvest and cultivars metrics
# only data from 2011 to 2014
post_province3=post_province_rheas_post
cultivars_post_province1=dataset2
rheas_post_prov_check=[]
province_metrics2=[]
for i in provinces:
    post_province1=post_province_rheas_post.loc[post_province_rheas_post['province_b']==i].reset_index(drop=True)
    cultivars_province2=cultivars_post_province1.loc[cultivars_post_province1['province_b']==i].reset_index(drop=True)

    #  pearson's correlation
    corr=cultivars_province2['yield'].corr(post_province1['yield'])

    # #root mean square error
    rmse = np.sqrt(((cultivars_province2['yield']-post_province1['yield'])**2).mean())
    # #unbiased RMSE
    ubrmse = np.sqrt((((cultivars_province2['yield']-cultivars_province2['yield'].mean())
                       -(post_province1['yield']-post_province1['yield'].mean()))**2).mean())
    # #bias
    bias = (cultivars_province2['yield']-post_province1['yield']).mean()
    # for i in districts:
    # metrics.extend([i, corr])
    province_metrics2.extend([[i, corr,rmse,ubrmse,bias]])
    # metrics.extend([i, corr])
    rheas_preharvest_prov_check.append(preharvest_province1)

check_rheas_preharvest_prov= pd.concat(rheas_preharvest_prov_check, ignore_index=True)

province_statistics2=pd.DataFrame(province_metrics2)
province_statistics2=province_statistics2.rename({0:'province',1: 
                                                  'correlation',2: 'rmse', 3:'ubrmse', 4:'bias'}, axis=1)

province_statistics2
province_statistics2

       province  correlation      rmse    ubrmse      bias
0       central     0.769980  1.962984  0.192172  1.953554
1    copperbelt     0.874979  1.842614  0.110947  1.839270
2       eastern    -0.121522  2.269356  0.091777  2.267499
3       luapula     0.719022  1.480009  0.050387  1.479151
4        lusaka     0.501059  1.923918  0.085281  1.922027
5      muchinga     0.650258  1.440975  0.129569  1.435138
6      northern     0.960482  1.603873  0.157855  1.596086
7  northwestern     0.856748  1.844209  0.234876  1.829191
8      southern     0.290188  2.720767  0.145441  2.716876
9       western    -0.259064  3.307551  0.232796  3.299349

In [19]:
# save postharvest_rheas_province_level_metrics
province_statistics2.to_csv('data/metrics/postharvest_rheas_province_level_metrics.csv', index=False)

In [20]:
# bias correcting cultivars using preharvest over the province
cultivars_post_province_grouped=cultivars_post_province1.groupby(['province_b'], as_index=False).agg({'yield':'mean'})
post_province=post_province.groupby(['province_b'],as_index=False).agg({'yield':'mean'})
post_province_renamed2=post_province.rename({'yield': 'post_yield'},axis=1)

# marge preharvest, metrics and cultivars cultivars yields
province_rheas_preharvest=pd.concat([cultivars_post_province_grouped,
                                     post_province_renamed2,province_statistics2], axis=1)

# calculate bias corrected yield
province_rheas_preharvest['corrected_yield']=(province_rheas_preharvest['yield'])-(province_rheas_preharvest['bias'])
province_rheas_preharvest

,province_b,yield,province_b,post_yield,province,correlation,rmse,ubrmse,bias,corrected_yield
0,central,4.031895,central,2.078341,central,0.769980,1.962984,0.192172,1.953554,2.078341
1,copperbelt,4.049430,copperbelt,2.210160,copperbelt,0.874979,1.842614,0.110947,1.839270,2.210160
2,eastern,4.035708,eastern,1.768208,eastern,-0.121522,2.269356,0.091777,2.267499,1.768208
3,luapula,4.033524,luapula,2.554374,luapula,0.719022,1.480009,0.050387,1.479151,2.554374
4,lusaka,4.037466,lusaka,2.115439,lusaka,0.501059,1.923918,0.085281,1.922027,2.115439
5,muchinga,4.057124,muchinga,2.621986,muchinga,0.650258,1.440975,0.129569,1.435138,2.621986
6,northern,4.036860,northern,2.440774,northern,0.960482,1.603873,0.157855,1.596086,2.440774
7,northwestern,4.045702,northwestern,2.216512,northwestern,0.856748,1.844209,0.234876,1.829191,2.216512
8,southern,4.031184,southern,1.314307,southern,0.290188,2.720767,0.145441,2.716876,1.314307
9,western,4.035516,western,0.736167,western,-0.259064,3.307551,0.232796,3.299349,0.736167

In [21]:
# bias correction

# cultivars_province['yield_corrected']
cultivars_preharvest_province=cultivars_province.groupby(['province_b'], as_index=False).agg({'yield':'mean'})
post_province=post_province.groupby(['province_b'], as_index=False).agg({'yield':'mean'})
post_province.rename({'province_b':'province_p','yield':'postharvest'},axis=1, inplace=True)
cultivars_preharvest_province['yield_corrected']=cultivars_preharvest_province['yield']-province_statistics2['bias']
rheas_postharvest_provincial=pd.concat([cultivars_preharvest_province,post_province,province_statistics2], axis=1)

rheas_postharvest_provincial1=rheas_postharvest_provincial[['province','yield','postharvest', 'yield_corrected','correlation', 
                              'rmse', 'ubrmse', 'bias']]
rheas_postharvest_provincial1.rename({'yield':'cultivars'},axis=1, inplace=True)
rheas_postharvest_provincial1

C:\Users\kasit\AppData\Local\Temp\ipykernel_16996\3299489503.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rheas_postharvest_provincial1.rename({'yield':'rheas'},axis=1, inplace=True)

,province,rheas,postharvest,yield_corrected,correlation,rmse,ubrmse,bias
0,central,4.009854,2.078341,2.056300,0.769980,1.962984,0.192172,1.953554
1,copperbelt,3.997637,2.210160,2.158366,0.874979,1.842614,0.110947,1.839270
2,eastern,4.008018,1.768208,1.740519,-0.121522,2.269356,0.091777,2.267499
3,luapula,4.012911,2.554374,2.533760,0.719022,1.480009,0.050387,1.479151
4,lusaka,4.008398,2.115439,2.086371,0.501059,1.923918,0.085281,1.922027
5,muchinga,4.018974,2.621986,2.583837,0.650258,1.440975,0.129569,1.435138
6,northern,4.019895,2.440774,2.423809,0.960482,1.603873,0.157855,1.596086
7,northwestern,4.016192,2.216512,2.187001,0.856748,1.844209,0.234876,1.829191
8,southern,4.009252,1.314307,1.292376,0.290188,2.720767,0.145441,2.716876
9,western,4.017791,0.736167,0.718442,-0.259064,3.307551,0.232796,3.299349